version: "2"

services:
    influxdb:
        image: influxdb:alpine
        container_name: influxdb
        volumes:
            - ./influxdb/var/lib:/var/lib/influxdb
        ports:
            - 8083:8083
            - 8086:8086
        restart: always

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        links:
          - influxdb

        volumes:
            - ./grafana/etc:/etc/grafana
            - ./grafana/var/lib:/var/lib/grafana
            - ./grafana/var/lib/plugins:/var/lib/grafana/plugins
            - ./grafana/var/log:/var/log/grafana
        ports:
            - 3000:3000
        restart: always
